### ISSUE TITLE
ng lint with angular 13 goes infinite

### ISSUE THREAD

**Issue by anandjaisy** [prettier/eslint-plugin-prettier#446]
**What version of `eslint` are you using?**
```
    "@angular-eslint/builder": "13.0.1",
    "@angular-eslint/eslint-plugin": "13.0.1",
    "@angular-eslint/eslint-plugin-template": "13.0.1",
    "@angular-eslint/schematics": "13.0.1",
    "@angular-eslint/template-parser": "13.0.1",
     "eslint": "^8.2.0"
```

**What version of `prettier` are you using?**
`"prettier": "^2.4.1",`

**What version of `eslint-plugin-prettier` are you using?**
```
"eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
```

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
**.eslintrc**
```
{
  "root": true,
  "ignorePatterns": [
    "projects/**/*"
  ],
  "overrides": [
    {
      "files": [
        "*.ts"
      ],
      "parserOptions": {
        "project": [
          "tsconfig.json",
          "e2e/tsconfig.json"
        ],
        "createDefaultProgram": true
      },
      "extends": [
        "plugin:@angular-eslint/recommended",
        "plugin:@angular-eslint/template/process-inline-templates",
        "plugin:prettier/recommended"
      ],
      "rules": {
        "@angular-eslint/component-selector": [
          "error",
          {
            // "prefix": "app",
            "style": "kebab-case",
            "type": "element"
          }
        ],
        "@angular-eslint/directive-selector": [
          "error",
          {
            // "prefix": "app",
            "style": "camelCase",
            "type": "attribute"
          }
        ],
        "@angular-eslint/no-host-metadata-property": "off",
        "@angular-eslint/no-output-on-prefix": "off",
        "@angular-eslint/no-output-native":"off",
        "@angular-eslint/no-input-rename": "off"
      }
    },
    {
      "files": [
        "*.html"
      ],
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ],
      "rules": {
        "@angular-eslint/template/eqeqeq": "off"
      }
    }
  ]
}
```
**.prettier**

```
{
    "semi": true,
    "trailingComma": "all",
    "singleQuote": true,
    "printWidth": 70
  }
```

**What source code are you linting?**
`ng lint` with Angular 13

**What did you expect to happen?**
Should lint all the files

**What actually happened?**
The lint process goes infinite

**Comment by JounQin** [comment]
Please try latest v4.1.0, it should have been fixed, feel free to comment if it doesn't.

**Comment by ShahinBelim** [comment]
I tried with the latest version and still facing this issue.
```  "@angular-eslint/builder": "^14.0.2",
    "@angular-eslint/eslint-plugin": "^14.0.2",
    "@angular-eslint/eslint-plugin-template": "^14.0.2",
    "@angular-eslint/schematics": "^14.0.2",
    "@angular-eslint/template-parser": "^14.0.2",
    "@typescript-eslint/eslint-plugin": "^5.39.0",
    "@typescript-eslint/parser": "^5.39.0",
    "eslint": "^8.24.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
```

**Comment by JounQin** [comment]
@ShahinBelim Then a minimal reproduction is required.
